config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.FAIR:
    repos:
      this_repo:
        commands:
        - fair-eva.py -ID https://zenodo.org/doi/10.5281/zenodo.4767771 -R oai-pmh
          -B https://zenodo.org/oai2d --tool_endpoint http://localhost:9090/v1.0/rda/rda_all
        container: qc.fair_thirsty-peach-bullfrog
timeout: 5400
